### ISSUE TITLE
Non-open source code?

### ISSUE THREAD

**Issue by sanity** [finmath/finmath-lib#15]
From [this file](https://github.com/finmath/finmath-lib/blob/master/src/main/java/net/finmath/optimizer/GoldenSectionSearch.java):

```
/* 
 * (c) Copyright Christian P. Fries, Germany. All rights reserved. Contact: email@christian-fries.de. 
 *  
 * Created on 25.01.2004 
 */ 
```

That would appear to contradict the Apache license this project is distributed under.

**Comment by student-t** [comment]
No it's not. The author has permission for anything. The Apache license applies to yourself, but not the author.

**Comment by sanity** [comment]
I'm not sure I understand.  "All rights reserved" means that content cannot be copied freely, which directly contradicts the Apache license.  Was this source code placed under Apache with the consent of the author, Christian Fries?

This could cause problems for anyone that uses this code if they go through due-diligence.

**Comment by cfries** [comment]
Hi Ian.

The code can be used under apache licence. Explanation can be found here:
 http://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved

With respect to your subject "non-open source code": Note that "open source" only refers to the fact that you can see the source code.

Yes, it is under the apache licence with the consent of me (the author).

**Comment by sanity** [comment]
Ok, fair enough, thanks for the reply :)
