### ISSUE TITLE
implement please Serializable interface in optimizer package

### ISSUE THREAD

**Issue by kicOLD** [finmath/finmath-lib#5]
hi!

I want to distrubute the optimizers (especially the LevenbergMarquardt) to different nodes in my hazelcast cluster. Therefore I would like to ask you if you could implement the Serializable interface to your optimizers.

Thanks and all the best
KIC

**Comment by cfries** [comment]
Done. I also improved the handling of NaN in values in setValues: NaN is interpreted as "reject parameter". - Please have a look.

**Comment by kic** [comment]
cool thanks! For the moment I am not running into NaN's, but I will see what happens :-)
