### ISSUE TITLE
Kotlin outdated

### ISSUE THREAD

**Issue by enalposi** [finmath/finmath-lib#79]
Hi. Thanks for the library!

Just a quick note that the Kotlin reference (1.2.0 from 2017) is somewhat outdated. I just spent quite a while debugging an issue, which turned out to be this 'elderly' Kotlin (indirectly referenced through a component and thus hidden in the dependency tree) quietly overtaking a directly referenced Kotlin 1.3 - and breaking the web server due to missing API. The Maven workaround is to exclude the Kotlin dependency of finmath but I figured I'd drop a related note here. Cheers.

**Comment by cfries** [comment]
Thanks. Kotlin was only used experimentally in a unit test. There is now a dedicated Kotlin wrapper http://www.finmath.net/finmath-lib-kotlin/ that also brings some more convenience. It is still experimental... feedback is welcomed.

**Comment by cfries** [comment]
Kotlin dependency will be removed from the lib. (I am sorry that you had this issue).

**Comment by enalposi** [comment]
No problem. I appreciate your work.

**Comment by cfries** [comment]
Fixed in 5.0.4. See also http://www.finmath.net/finmath-lib-kotlin/
