### ISSUE TITLE
Change default behaviours with system properties

### ISSUE THREAD

**Issue by William1104** [finmath/finmath-lib#9]
Hi Christian, 

Some classes (e.g. LinearAlgebra, CalibrationSpec and LIBORMarketModelStandard) control default behaviours with some embedded variables. Those variable values can be changed only with code changes. 

May I modify related classes, so that those variable values can be changed with some system properties? I will keep the code backward compatible. 

Best regards,
William

**Comment by cfries** [comment]
I am considering removing the dependency to colt (which would remove the need for a property in LinearAlgebra) and use parameter in LIBORMarketModelStandard. (Note that LIBORMarketModelStandard is a legacy class and all the features are now in LIBORMarketModel). What do you think?

**Comment by oliverdauben** [comment]
Go for it. I've got the Impression that the project is no longer under any maintenance at all.

**Comment by cfries** [comment]
I have removed the dependency to colt. But since commons-math is slow, I have added a dependency to jblas. It can be configured via a Java properties file. The default behavior is to use jblas and commons-math as a default on system where jblas is not available (jblas needs some binary libs).

**Comment by William1104** [comment]
Many thanks for accepting the idea. :)
